import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Camera, CheckCircle2, Clock3, Loader2, LogOut, ShieldCheck, Stethoscope, Video } from 'lucide-react';
import { authApi, CurrentActor } from '../../lib/auth';
import { JoinGrant, Teleconsultation, teleconsultationApi } from '../../lib/teleconsultationApi';
import { JitsiConsultation } from './JitsiConsultation';

export function VirtualOpdPortal() {
  const [actor, setActor] = useState<CurrentActor | null>(null); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [items, setItems] = useState<Teleconsultation[]>([]); const [active, setActive] = useState<Teleconsultation | null>(null);
  const [grant, setGrant] = useState<JoinGrant | null>(null); const [devicesReady, setDevicesReady] = useState(false);

  const refresh = useCallback(async (current: CurrentActor, selectedId?: string) => {
    const found = current.role === 'doctor' ? await teleconsultationApi.doctorAppointments() :
      await teleconsultationApi.patientAppointments().then(async values => Promise.all(values.map(value => teleconsultationApi.patientView(value.id))));
    setItems(found); const wanted = selectedId || new URLSearchParams(location.search).get('appointment');
    setActive(found.find(item => item.appointment_id === wanted) || found[0] || null);
  }, []);
  useEffect(() => { authApi.me().then(async value => { setActor(value); await refresh(value); }).catch(() => undefined).finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => {
    if (!actor || !active || active.status === 'completed' || grant) return;
    const timer = window.setInterval(() => void refresh(actor, active.appointment_id).catch(() => undefined), 7000);
    return () => window.clearInterval(timer);
  }, [actor, active, grant, refresh]);
  const login = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const value = email.trim().toUpperCase().startsWith('EXO-P-') ? await authApi.patientCodeLogin(email, password) : await authApi.login(email, password); if (!['patient', 'doctor'].includes(value.role)) throw new Error('A patient or doctor account is required.'); setActor(value); await refresh(value); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Sign in failed.'); } finally { setLoading(false); } };
  const act = async (operation: () => Promise<Teleconsultation>) => { setLoading(true); setError(''); try { const value = await operation(); setActive(value); if (actor) await refresh(actor, value.appointment_id); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The action could not be completed.'); } finally { setLoading(false); } };
  const join = async () => { if (!active || !actor) return; setLoading(true); setError(''); try { setGrant(actor.role === 'doctor' ? await teleconsultationApi.doctorGrant(active.appointment_id) : await teleconsultationApi.patientGrant(active.appointment_id)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to join.'); } finally { setLoading(false); } };
  const checkDevices = async () => { setError(''); try { const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); stream.getTracks().forEach(track => track.stop()); setDevicesReady(true); } catch { setError('Camera and microphone access is required. Check browser permissions and try again.'); } };
  if (loading && !actor) return <Shell><Loader2 className="size-8 animate-spin" /></Shell>;
  if (!actor) return <Shell><form onSubmit={login} className="w-full max-w-md bg-white border rounded-3xl p-8 shadow-xl"><ShieldCheck className="size-10 text-[#154734]"/><h1 className="mt-5 text-3xl font-semibold">Virtual OPD</h1><p className="mt-2 text-sm text-[#66756d]">Patients can use an email or EXO-P patient code. Doctors use their hospital email.</p><input className="mt-6 w-full h-12 border rounded-xl px-4" type="text" placeholder="Email or patient code" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/><input className="mt-3 w-full h-12 border rounded-xl px-4" type="password" placeholder="Password or access code" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/>{error&&<p className="mt-3 text-sm text-rose-700">{error}</p>}<button className="mt-5 w-full h-12 bg-[#154734] text-white rounded-xl font-semibold" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></Shell>;
  return <div className="min-h-screen bg-[#f4f6f3] text-[#16241d]"><header className="h-18 bg-white border-b px-5 flex justify-between items-center"><a href="/" className="text-xl font-serif-logo">avocado</a><div className="flex items-center gap-4 text-sm"><span>{actor.display_name} · {actor.role}</span><button onClick={()=>void authApi.logout().then(()=>location.reload())}><LogOut className="size-4"/></button></div></header><main className="max-w-7xl mx-auto p-5 sm:p-8"><div className="grid lg:grid-cols-[310px_1fr] gap-6"><aside className="space-y-3"><h1 className="text-2xl font-semibold">Virtual OPD</h1><p className="text-sm text-[#66756d]">{actor.role==='doctor'?'Your assigned consultations':'Your video appointments'}</p>{items.map(item=><button key={item.id} onClick={()=>{setActive(item);setGrant(null)}} className={`w-full text-left p-4 rounded-2xl border ${active?.id===item.id?'bg-[#154734] text-white':'bg-white'}`}><p className="font-semibold">{actor.role==='doctor' ? item.patient?.name||'Patient consultation' : item.doctor?.name||'Video consultation'}</p><p className="text-xs opacity-70 mt-1">{new Date(item.starts_at).toLocaleString()} · {item.status}</p></button>)}{!items.length&&<div className="bg-white border rounded-2xl p-5 text-sm">No virtual appointments found.</div>}</aside><section className="bg-white border rounded-3xl p-5 sm:p-7 min-h-[580px]">{error&&<div className="mb-5 p-3 bg-rose-50 text-rose-800 rounded-xl">{error}</div>}{!active?<div className="h-96 grid place-items-center text-[#66756d]">Select a consultation.</div>:grant?<><JitsiConsultation grant={grant} onHangup={()=>setGrant(null)}/><div className="mt-4 flex justify-end">{actor.role==='doctor'&&<button onClick={()=>void act(()=>teleconsultationApi.end(active.appointment_id)).then(()=>setGrant(null))} className="px-5 h-11 rounded-xl bg-rose-700 text-white font-semibold">End consultation</button>}</div></>:<ConsultationCard actor={actor} item={active} devicesReady={devicesReady} checkDevices={checkDevices} act={act} join={join} loading={loading}/>}</section></div></main></div>;
}

function ConsultationCard({actor,item,devicesReady,checkDevices,act,join,loading}:{actor:CurrentActor;item:Teleconsultation;devicesReady:boolean;checkDevices:()=>Promise<void>;act:(operation:()=>Promise<Teleconsultation>)=>Promise<void>;join:()=>Promise<void>;loading:boolean}) { const patient=actor.role==='patient'; return <div><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-[#49705c] font-bold">{item.status}</p><h2 className="mt-2 text-3xl font-semibold">{patient ? item.doctor?.name||'Video consultation' : item.patient?.name||'Patient consultation'}</h2><p className="mt-2 text-[#66756d]">{new Date(item.starts_at).toLocaleString()}</p>{!patient&&item.patient?.phone&&<p className="mt-1 text-sm text-[#66756d]">{item.patient.phone}</p>}</div><Video className="size-9 text-[#154734]"/></div><div className="mt-7 grid sm:grid-cols-2 gap-4"><Status icon={ShieldCheck} title="Telemedicine consent" done={item.consent_accepted}/><Status icon={Camera} title="Camera and microphone" done={devicesReady}/><Status icon={Clock3} title="Consultation status" detail={item.status}/><Status icon={Stethoscope} title={patient?'Doctor':'Patient'} detail={patient?item.doctor?.name:item.patient?.name}/></div><div className="mt-8 flex flex-wrap gap-3">{patient&&!item.consent_accepted&&<button onClick={()=>void act(()=>teleconsultationApi.consent(item.appointment_id,item.consent_version))} className="h-12 px-5 bg-[#154734] text-white rounded-xl font-semibold">Accept consent</button>}{!devicesReady&&<button onClick={()=>void checkDevices()} className="h-12 px-5 border rounded-xl font-semibold">Check camera and microphone</button>}{patient&&item.consent_accepted&&item.status==='scheduled'&&<button onClick={()=>void act(()=>teleconsultationApi.checkIn(item.appointment_id))} className="h-12 px-5 bg-[#154734] text-white rounded-xl font-semibold">Enter waiting room</button>}{!patient&&item.status!=='in_progress'&&item.status!=='completed'&&<button onClick={()=>void act(()=>teleconsultationApi.start(item.appointment_id))} className="h-12 px-5 bg-[#154734] text-white rounded-xl font-semibold">Start consultation</button>}{item.status==='in_progress'&&devicesReady&&<button onClick={()=>void join()} disabled={loading} className="h-12 px-6 bg-[#154734] text-white rounded-xl font-semibold">Join secure video</button>}</div>{patient&&item.status==='waiting'&&<p className="mt-6 p-4 bg-amber-50 rounded-xl text-sm">You are checked in. This page will update when your doctor starts.</p>}{item.status==='completed'&&<div className="mt-7 p-5 bg-emerald-50 rounded-2xl"><CheckCircle2 className="text-emerald-700"/><p className="mt-2 font-semibold">Consultation completed</p><p className="text-sm mt-1">Clinical documents will appear here when available from the HMS.</p></div>}</div> }
function Status({icon:Icon,title,done,detail}:{icon:typeof Camera;title:string;done?:boolean;detail?:string}) { return <div className="border rounded-2xl p-4 flex gap-3"><Icon className="size-5 text-[#154734]"/><div><p className="font-semibold text-sm">{title}</p><p className="text-xs text-[#66756d] mt-1">{done?'Ready':detail||'Required'}</p></div></div> }
function Shell({children}:{children:React.ReactNode}) { return <div className="min-h-screen bg-[#f4f6f3] grid place-items-center p-6">{children}</div> }
