import { ArrowUpRight, Phone, Check } from 'lucide-react';
import { clientPackages } from '../../data/clientPackages';
const formatPrice = (amount: number) => `₹${amount.toLocaleString('en-IN')}`;
const notes: Record<string, string> = {
  'diabetic-check-up': 'Ask how this focused check compares with the broader diabetic profile.',
  'fertility-health-check-up': 'Discuss the assessment with the care team and confirm who the package is designed for.',
  'general-diabetic-health-check-up': 'Check the test list and discuss how it fits your existing diabetes care.',
  'advance-health-check-up': 'Review the full test list with reception before choosing this screening option.',
  'antenatal-profile': 'Your obstetrician can advise which prenatal assessments suit your stage of pregnancy.',
  'general-health-check-up': 'Confirm the routine screening tests included and whether a consultation is part of the package.',
  'complete-health-check-up': 'Ask for the complete test list and review its suitability with your doctor.',
  'cardiac-health-check-up': 'Confirm the cardiac tests included; your doctor can advise the right assessment for you.',
};
export function AllHealthPackages() {
  return <section id="all-packages" className="scroll-mt-28 bg-[#fbfaf6] py-16 sm:py-24"><div className="mx-auto max-w-[1400px] px-5 sm:px-10 lg:px-16">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">HEALTH CHECKS</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">All eight health packages.</h2><p className="mt-5 max-w-2xl leading-relaxed text-[#617367]">Compare the hospital’s published check-up options in one place. Each price is for a one-time package.</p></div><span className="shrink-0 text-sm text-[#65776b]">One-time check-ups</span></div>
    <div className="mt-10 grid gap-4 md:grid-cols-2">{clientPackages.map((item, index) => <article key={item.id} data-package={item.id} className="flex flex-col rounded-2xl border border-[#dce6d9] bg-white p-6 sm:p-9"><div className="flex items-start justify-between gap-3"><span className="text-xs tabular-nums text-[#7e9e7f]">0{index + 1}</span><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#65816a]">Health package</span></div><h3 className="mt-5 text-2xl font-medium leading-tight tracking-[-.025em] sm:text-3xl">{item.name}</h3><p className="mt-3 text-sm leading-relaxed text-[#617367]">{item.description}</p><div className="mt-7 flex flex-wrap items-baseline gap-3"><span className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">{formatPrice(item.price)}</span><del className="text-sm text-[#849184]">{formatPrice(item.originalPrice)}</del></div><p className="mt-2 text-xs text-[#65776b]">Published offer price · confirm current availability</p><p className="mt-6 border-t border-[#e0e8dc] pt-5 text-sm leading-relaxed text-[#617367]">{notes[item.id]}</p><a href="tel:+919901711716" aria-label={`Ask about ${item.name}`} className="mt-auto inline-flex items-center gap-2 self-start pt-6 text-sm font-semibold text-[#275c40]">Ask about this package <ArrowUpRight size={16} /></a></article>)}</div>
    <div className="mt-10 grid gap-8 rounded-2xl bg-[#e8f0e5] p-7 sm:p-10 lg:grid-cols-2"><div><h3 className="text-2xl font-medium tracking-[-.025em]">Know exactly what you’re booking.</h3><p className="mt-4 text-sm leading-relaxed text-[#617367]">The published package list does not specify every included test or preparation instruction. Reception can provide the current inclusions, any consultation benefit and offer validity before you decide.</p><a href="tel:+919901711716" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#275c40]"><Phone size={16} /> Call 99017 11716</a></div><ul className="space-y-4 text-sm text-[#496050]">{['Ask for the full test and consultation list.', 'Confirm fasting, medicine and appointment instructions.', 'Check the final price, offer validity and any extra charges.', 'Ask your doctor which package is appropriate for you.'].map(text => <li key={text} className="flex gap-3"><Check size={17} className="mt-0.5 shrink-0 text-[#477456]" />{text}</li>)}</ul></div>
  </div></section>;
}
