import { FileText, Phone, ShieldCheck } from 'lucide-react';

// Names and workflow: https://slsshospitals.com/cashless-insurance/.
const insurers = ['Bajaj Allianz', 'ICICI Lombard', 'Max Bupa', 'HDFC ERGO', 'Star Health'];
const schemes = ['Arogya Sri', 'ABARK', 'ESI', 'BBMP'];
const steps = [
  { title: 'Verify your insurance', copy: 'Contact the hospital insurance desk with your insurer, policy or scheme details. Ask whether your cover applies at this hospital and to the planned treatment.' },
  { title: 'Prepare the documents', copy: 'The desk will explain the documents needed for your case and help with claim information. Keep policy details and your medical records ready.' },
  { title: 'Request pre-authorization', copy: 'The hospital submits the treatment information to your insurer or TPA for approval. The approved amount and conditions determine what can be settled cashlessly.' },
  { title: 'Receive the planned care', copy: 'Once approval is available, the team explains the next steps for your treatment. Ask about any deposit, copay or charges outside the approved cover.' },
  { title: 'Discharge & settlement', copy: 'The hospital coordinates the final claim settlement with your insurer. Review the final bill and any amount you need to pay before discharge.' },
];
const faqs = [
  { title: 'Does cashless mean everything is free?', copy: 'Cashless means eligible, approved charges can be settled between the hospital and your insurer. Deductibles, copays, excluded items or costs above your approved limit may still be payable by you.' },
  { title: 'Are consultations and health packages covered?', copy: 'Outpatient consultations, tests and preventive health packages may have different benefits from hospitalization. Check your specific policy with the insurer and hospital desk before booking.' },
  { title: 'What if my insurer is not listed here?', copy: 'Call the insurance desk with your insurer and TPA details. The names shown here come from the hospital’s public website and do not represent every current arrangement.' },
  { title: 'How do government schemes work?', copy: 'Scheme eligibility, required identification, treatment scope and approvals vary. Ask the desk to check your scheme and the care you need before assuming cashless admission is available.' },
  { title: 'Can I check eligibility online?', copy: 'For now, the hospital insurance desk confirms eligibility directly. The website does not provide a live policy verification or pre-authorization service.' },
];
export function CashlessGuide() {
  return <>
    <section className="bg-[#e8f0e5] py-16 sm:py-20"><div className="mx-auto max-w-[1240px] px-5 sm:px-10 lg:px-14"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">UNDERSTANDING CASHLESS CARE</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">More clarity.<br />Less paperwork.</h2><p className="mt-5 max-w-xl leading-relaxed text-[#5c6e61]">For eligible treatment, cashless care lets the hospital coordinate approved payments with your insurer or third-party administrator (TPA). The insurance desk guides you through documentation, authorization and settlement.</p></div><aside className="rounded-2xl bg-white p-7 sm:p-9"><ShieldCheck size={26} strokeWidth={1.5} className="text-[#477456]" /><h3 className="mt-5 text-2xl font-medium">Know your share of the cost.</h3><p className="mt-4 text-sm leading-relaxed text-[#617367]">Approval depends on your policy, treatment and insurer. Ask for a clear estimate of any copay, deductible, exclusions and charges beyond your approved cover.</p><a href="tel:+919901711716" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#275c40]"><Phone size={16} /> Speak to the insurance desk</a></aside></div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-16 sm:px-10 sm:py-20 lg:px-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">YOUR CASHLESS JOURNEY</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Five steps, with support.</h2><div className="mt-10 divide-y divide-[#dce6d9] border-y border-[#dce6d9]">{steps.map((step, index) => <article key={step.title} className="grid gap-4 py-7 sm:grid-cols-[50px_1fr_1.5fr] sm:gap-8 sm:py-9"><span className="text-sm font-medium text-[#7e9e7f]">0{index + 1}</span><h3 className="text-2xl font-medium tracking-[-.025em]">{step.title}</h3><p className="text-sm leading-relaxed text-[#617367]">{step.copy}</p></article>)}</div></section>
    <section className="bg-[#eef3eb] py-16 sm:py-20"><div className="mx-auto max-w-[1240px] px-5 sm:px-10 lg:px-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">INSURANCE & SCHEMES</p><h2 className="mt-4 max-w-xl text-4xl font-medium tracking-[-.04em] sm:text-5xl">Start with the cover you have.</h2><div className="mt-9 grid gap-5 md:grid-cols-2"><article className="rounded-2xl bg-white p-7 sm:p-9"><h3 className="text-2xl font-medium">Private insurance</h3><p className="mt-3 text-sm leading-relaxed text-[#617367]">The hospital’s website names these insurers. The desk can confirm your policy and current network arrangement.</p><ul className="mt-6 flex flex-wrap gap-2">{insurers.map(name => <li key={name} className="rounded-full border border-[#dce6d9] px-4 py-2 text-sm text-[#496050]">{name}</li>)}</ul></article><article className="rounded-2xl bg-white p-7 sm:p-9"><h3 className="text-2xl font-medium">Government schemes</h3><p className="mt-3 text-sm leading-relaxed text-[#617367]">Arogya Sri, ABARK and ESI appear on the cashless page; BBMP is also listed on the homepage. Check eligibility and treatment approval with the desk.</p><ul className="mt-6 flex flex-wrap gap-2">{schemes.map(name => <li key={name} className="rounded-full border border-[#dce6d9] px-4 py-2 text-sm text-[#496050]">{name}</li>)}</ul></article></div><p className="mt-5 text-xs leading-relaxed text-[#617367]">Insurer and scheme names follow the hospital’s published information. Participation, approved treatments and policy benefits should be confirmed for your visit.</p></div></section>
    <section className="mx-auto grid max-w-[1240px] gap-10 px-5 py-16 sm:px-10 sm:py-20 lg:grid-cols-[.85fr_1.15fr] lg:gap-20 lg:px-14"><div><FileText size={26} strokeWidth={1.5} className="text-[#477456]" /><h2 className="mt-5 text-3xl font-medium tracking-[-.035em] sm:text-4xl">Before you arrive.</h2><p className="mt-4 text-sm leading-relaxed text-[#617367]">Ask the desk for the exact document checklist for your policy and treatment. It helps to have these ready for the conversation:</p><ul className="mt-6 space-y-4 text-sm text-[#496050]">{['Insurance card, policy number or scheme details', 'Patient identification details', 'Recent medical reports and any referral', 'The planned treatment or admission information'].map(item => <li key={item} className="flex gap-3"><span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-[#7e9e7f]" />{item}</li>)}</ul></div><div><h2 className="text-3xl font-medium tracking-[-.035em] sm:text-4xl">Questions worth asking.</h2><div className="mt-7 divide-y divide-[#dce6d9] border-y border-[#dce6d9]">{faqs.map(faq => <details key={faq.title} className="group py-5"><summary className="cursor-pointer text-base font-medium leading-relaxed marker:text-[#7e9e7f]">{faq.title}</summary><p className="mt-4 text-sm leading-relaxed text-[#617367]">{faq.copy}</p></details>)}</div></div></section>
  </>;
}
