import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, ArrowLeft, ArrowRight, Play, X, Maximize2 } from 'lucide-react';
import { Breadcrumbs } from '../common/Breadcrumbs';
import { hospitalPhotographs, hospitalVideos } from '../../data/clientMedia';
import { YouTubePlayer } from '../media/YouTubePlayer';

const shell = 'mx-auto max-w-[1400px] px-5 sm:px-10 lg:px-16';
type Photo = typeof hospitalPhotographs[number];
export function CommunityMediaPage({ onBackToHome, onExploreFacilities }: { onBackToHome: () => void; onExploreFacilities: () => void }) {
  const [filter, setFilter] = useState<'All' | 'Hospital' | 'Community'>('All');
  const [videoId, setVideoId] = useState(hospitalVideos[0].id);
  const [selectedPhoto, setSelectedPhoto] = useState<Photo | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const photoTrigger = useRef<HTMLButtonElement | null>(null);
  useEffect(() => { if (selectedPhoto && !dialog.current?.open) dialog.current?.showModal(); }, [selectedPhoto]);
  const photos = hospitalPhotographs.filter(photo => filter === 'All' || photo.category === filter);
  const video = hospitalVideos.find(item => item.id === videoId)!;
  const selectedIndex = photos.findIndex(photo => photo.id === selectedPhoto?.id);
  const movePhoto = (offset: number) => setSelectedPhoto(photos[(selectedIndex + offset + photos.length) % photos.length]);
  const chooseVideo = (id: string) => {
    setVideoId(id);
    if (window.innerWidth < 1024) document.getElementById('featured-film')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' });
  };
  const openPhoto = (photo: Photo, trigger: HTMLButtonElement) => { photoTrigger.current = trigger; setSelectedPhoto(photo); };
  return <div className="bg-[#fbfaf6] text-[#17372b]">
    <div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'Community & media' }]} /></div>
    <section className={`${shell} grid gap-10 py-14 lg:grid-cols-[1.05fr_1fr] lg:items-center lg:gap-16 lg:py-20`}>
      <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">LIFE AT SRI LAKSHMI</p><h1 className="mt-5 text-[clamp(3.4rem,6vw,6.3rem)] font-medium leading-[.98] tracking-[-.055em]">Care connects<br />a community.</h1><p className="mt-7 max-w-lg text-lg leading-relaxed text-[#5c6e61]">Meet the people, explore our hospital and see the moments we share beyond the consultation room.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#films" className="inline-flex items-center gap-2 rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white"><Play size={16} /> Watch our films</a><a href="#photo-library" className="inline-flex items-center gap-2 rounded-full border border-[#9ab29e] px-6 py-3.5 text-sm font-semibold">Explore photographs <ArrowDown size={16} /></a></div></div>
      <figure className="m-0"><div className="aspect-[1.15] overflow-hidden rounded-[1.8rem]"><img src={hospitalPhotographs[6].src} alt={hospitalPhotographs[6].caption} className="h-full w-full object-cover" /></div><figcaption className="mt-4 flex items-center justify-between gap-4 text-xs text-[#65776b]"><span>Moments from our wider hospital community</span><span className="shrink-0">Sri Lakshmi Group</span></figcaption></figure>
    </section>
    <section id="films" className="scroll-mt-28 bg-[#17372b] py-16 text-[#f7f7ee] sm:py-20"><div className={shell}>
      <div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#b1c9b1]">IN THEIR OWN WORDS</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Stories from Sri Lakshmi.</h2></div><p className="max-w-xs text-sm leading-relaxed text-[#b8cabd]">Founder conversations, doctor explainers and events from the group’s official YouTube channel.</p></div>
      <div className="grid gap-9 lg:grid-cols-[1.8fr_1fr] lg:gap-10">
        <div id="featured-film" className="min-w-0 scroll-mt-28"><YouTubePlayer key={video.id} video={video} /><p className="mt-7 text-xs font-semibold uppercase tracking-[.15em] text-[#b1c9b1]">{video.category}</p><h3 className="mt-3 text-2xl font-medium tracking-[-.025em] sm:text-3xl">{video.title}</h3><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#b8cabd]">{video.description}</p></div>
        <div aria-label="Choose a video" className="divide-y divide-white/15 border-y border-white/15">{hospitalVideos.map((item, i) => <button key={item.id} onClick={() => chooseVideo(item.id)} aria-pressed={item.id === videoId} className={`group flex w-full items-center gap-4 px-3 py-5 text-left transition-colors focus-visible:outline-2 focus-visible:outline-[#d3e5ca] ${item.id === videoId ? 'bg-white/10' : 'hover:bg-white/5'}`}><span className="shrink-0 text-xs tabular-nums text-[#b1c9b1]">0{i + 1}</span><span className="min-w-0 flex-1"><span className="block text-[10px] font-semibold uppercase tracking-[.12em] text-[#b1c9b1]">{item.category}</span><span className="mt-2 block text-sm leading-snug sm:text-base">{item.title}</span></span><Play size={15} className={`shrink-0 ${item.id === videoId ? 'fill-current' : 'opacity-40'}`} /></button>)}</div>
      </div>
      <p className="mt-10 border-t border-white/15 pt-5 text-xs leading-relaxed text-[#b8cabd]">Videos open in the embedded YouTube player when you press play. Group events and hospital tours may feature other Sri Lakshmi locations. For personal medical advice, speak with your treating doctor.</p>
    </div></section>
    <section id="photo-library" className={`${shell} scroll-mt-28 py-16 sm:py-24`}>
      <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#65816a]">THE PHOTO JOURNAL</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Places, people & shared moments.</h2></div><span className="text-sm text-[#65776b]">{photos.length} photographs</span></div>
      <div className="mt-8 flex flex-wrap gap-2" aria-label="Filter photographs">{(['All', 'Hospital', 'Community'] as const).map(label => <button key={label} onClick={() => setFilter(label)} aria-pressed={filter === label} className={`rounded-full border px-5 py-2.5 text-sm font-medium transition-colors ${filter === label ? 'border-[#214f38] bg-[#214f38] text-white' : 'border-[#d2dece] hover:bg-[#e8f0e5]'}`}>{label === 'All' ? 'All photographs' : label === 'Hospital' ? 'Inside the hospital' : 'Community & events'}</button>)}</div>
      <div className="mt-8 grid gap-x-5 gap-y-9 sm:grid-cols-2 lg:grid-cols-3">{photos.map(photo => <figure key={photo.id} className={`m-0 min-w-0 ${photo.wide ? 'sm:col-span-2' : ''}`}><button onClick={event => openPhoto(photo, event.currentTarget)} aria-label={`View photo: ${photo.title}`} className={`group relative block w-full overflow-hidden rounded-2xl bg-[#e5eee2] ${photo.wide ? 'aspect-[1.5] sm:aspect-[2.1]' : 'aspect-[1.5] sm:aspect-[1.03]'}`}><img src={photo.src} alt={photo.caption} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 motion-safe:group-hover:scale-[1.035]" /><span className="absolute bottom-4 right-4 flex size-9 items-center justify-center rounded-full bg-white/90 text-[#17372b] shadow-sm"><Maximize2 size={15} /></span></button><figcaption className="mt-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#65816a]">{photo.category === 'Community' ? 'Across the hospital group' : 'Hospital gallery'}</p><h3 className="mt-2 text-xl font-medium tracking-[-.025em]">{photo.title}</h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#65776b]">{photo.caption}</p></figcaption></figure>)}</div>
    </section>
    <section className="bg-[#e8f0e5] py-14"><div className={`${shell} flex flex-col justify-between gap-6 sm:flex-row sm:items-center`}><div><h2 className="text-3xl font-medium tracking-[-.035em]">Get to know our facilities.</h2><p className="mt-3 text-sm text-[#5c6e61]">Explore the technology and care spaces behind our hospital services.</p></div><button onClick={onExploreFacilities} className="inline-flex items-center gap-2 self-start rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white">Facilities & technology <ArrowUpRight size={16} /></button></div></section>
    <dialog ref={dialog} aria-label="Hospital photo viewer" onClick={event => { if (event.target === event.currentTarget) dialog.current?.close(); }} onClose={() => { setSelectedPhoto(null); photoTrigger.current?.focus({ preventScroll: true }); }} onKeyDown={event => { if (event.key === 'ArrowLeft') movePhoto(-1); if (event.key === 'ArrowRight') movePhoto(1); }} className="fixed inset-0 m-auto max-h-[92dvh] w-[calc(100%_-_2rem)] max-w-5xl overflow-auto rounded-2xl border-0 bg-[#fbfaf6] p-0 text-[#17372b] shadow-2xl backdrop:bg-black/80">
      {selectedPhoto && <><div className="flex items-center justify-between gap-4 px-5 py-4"><p className="text-xs font-medium text-[#65776b]">{selectedIndex + 1} / {photos.length} · {selectedPhoto.category}</p><button onClick={() => dialog.current?.close()} aria-label="Close photo viewer" className="rounded-full p-2 hover:bg-[#e8f0e5]"><X size={20} /></button></div><img src={selectedPhoto.src} alt={selectedPhoto.caption} className="max-h-[65dvh] w-full object-contain" /><div className="flex items-center justify-between gap-4 p-5 sm:p-7"><div><h2 className="text-xl font-medium">{selectedPhoto.title}</h2><p className="mt-2 text-sm leading-relaxed text-[#65776b]">{selectedPhoto.caption}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => movePhoto(-1)} aria-label="Previous photo" className="rounded-full border border-[#c3d1c0] p-2 hover:bg-[#e8f0e5]"><ArrowLeft size={18} /></button><button onClick={() => movePhoto(1)} aria-label="Next photo" className="rounded-full border border-[#c3d1c0] p-2 hover:bg-[#e8f0e5]"><ArrowRight size={18} /></button></div></div></>}
    </dialog>
  </div>;
}
