import { ArrowUpRight, HeartPulse, Activity, Droplets, ScanLine, Microscope, Pill, Phone, Stethoscope } from 'lucide-react';
import { Breadcrumbs } from '../common/Breadcrumbs';
import { clientAsset } from '../../data/clientAssets';

const shell = 'mx-auto max-w-[1400px] px-5 sm:px-10 lg:px-16';
const facilities = [
  { icon: HeartPulse, label: 'CARDIAC CARE', title: 'Philips FD10 cardiac cath lab', description: 'The hospital lists a Philips FD10 catheterization laboratory for cardiac investigations and interventional care.', details: ['Digital imaging for cardiac catheterization', 'Coronary angiography', 'Angioplasty and stent procedures'], department: 'cardiology', action: 'Explore cardiology' },
  { icon: Activity, label: 'UROLOGY', title: '100-watt Holmium laser', description: 'Holmium laser technology is listed for kidney stone and prostate procedures. Your urologist assesses whether laser treatment is appropriate.', details: ['Laser treatment for urinary stones', 'Prostate procedure support', 'Specialist assessment and treatment planning'], department: 'urology', action: 'Explore urology' },
  { icon: HeartPulse, label: 'CRITICAL CARE', title: '10-bed intensive care unit', description: 'A dedicated ICU for patients who need close observation and critical care support, with monitoring and life-support equipment.', details: ['Vital-sign monitoring and ventilators', 'Infusion pumps and defibrillators', 'Dialysis equipment for critical-care support'], department: 'emergency', action: 'Explore emergency care' },
  { icon: Droplets, label: 'RENAL CARE', title: '10-bed dialysis unit', description: 'The hospital lists a dedicated dialysis unit with hemodialysis equipment for patients whose treatment plan includes dialysis.', details: ['Hemodialysis services', 'Dedicated treatment spaces', 'Coordinate sessions with the renal-care team'], department: 'nephrology', action: 'Explore kidney care' },
  { icon: Stethoscope, label: 'SURGICAL CARE', title: 'Modular operating theatre', description: 'A modular operating theatre designed for surgical care, with controlled airflow and filtration described by the hospital.', details: ['HEPA air filtration', 'Laminar airflow systems', 'General and laparoscopic surgical care'], department: 'general-surgery', action: 'Explore surgical care' },
  { icon: ScanLine, label: 'DIAGNOSTIC SERVICES', title: 'Echo & ultrasound', description: 'Echocardiography and ultrasound services support clinical evaluation. The treating team advises which examination you need.', details: ['Echocardiography for heart assessment', 'Ultrasound examinations', 'Confirm test availability and preparation'], department: 'radiology', action: 'Explore diagnostic care' },
];
export function FacilitiesPage({ onBackToHome, onExploreCommunity, onSelectDepartment }: { onBackToHome: () => void; onExploreCommunity: () => void; onSelectDepartment: (id: string) => void }) {
  return <div className="bg-[#fbfaf6] text-[#17372b]">
    <div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'Facilities & technology' }]} /></div>
    <section className={`${shell} grid gap-12 py-16 lg:grid-cols-2 lg:items-center lg:py-24`}><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">BEHIND YOUR CARE</p><h1 className="mt-5 text-[clamp(3.4rem,6vw,6.4rem)] font-medium leading-[.98] tracking-[-.055em]">Technology.<br />Spaces.<br />Support.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#5c6e61]">Explore the facilities published by Sri Lakshmi Super Speciality Hospital, from cardiac and renal care to surgical and diagnostic services.</p><a href="#facility-guide" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white">Explore our facilities <ArrowUpRight size={16} /></a></div><figure className="m-0"><img src={clientAsset('2024/12/1-3.png')} alt="The hospital’s cardiac catheterization laboratory" className="aspect-[1.04] w-full rounded-[1.8rem] object-cover" /><figcaption className="mt-4 text-xs text-[#65776b]">Inside the hospital’s cardiac cath lab</figcaption></figure></section>
    <section id="facility-guide" className="scroll-mt-28 bg-[#e8f0e5] py-16 sm:py-20"><div className={shell}><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">FACILITIES & TECHNOLOGY</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-[-.04em] sm:text-5xl">Support for every stage of care.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{facilities.map(facility => <article key={facility.title} className="flex flex-col rounded-2xl bg-white p-7 sm:p-8"><facility.icon size={26} strokeWidth={1.4} className="text-[#477456]" /><p className="mt-7 text-[10px] font-bold tracking-[.16em] text-[#65816a]">{facility.label}</p><h3 className="mt-3 text-2xl font-medium leading-tight tracking-[-.03em]">{facility.title}</h3><p className="mt-4 text-sm leading-relaxed text-[#617367]">{facility.description}</p><ul className="mt-6 space-y-3 border-t border-[#e0e8dc] pt-5 text-sm text-[#496050]">{facility.details.map(detail => <li key={detail} className="flex gap-2"><span className="mt-2 size-1 shrink-0 rounded-full bg-[#7e9e7f]" />{detail}</li>)}</ul><button onClick={() => onSelectDepartment(facility.department)} className="mt-auto inline-flex items-center gap-2 self-start pt-7 text-sm font-semibold text-[#275c40]">{facility.action} <ArrowUpRight size={16} /></button></article>)}</div></div></section>
    <section className={`${shell} grid gap-10 py-16 lg:grid-cols-2 lg:items-center sm:py-24`}><img src={clientAsset('2024/12/1-6.png')} alt="Hospital laboratory staff working with diagnostic equipment" loading="lazy" className="aspect-[1.15] w-full rounded-2xl object-cover" /><div className="lg:pl-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#65816a]">EVERYDAY SUPPORT</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Here around the clock.</h2><p className="mt-5 leading-relaxed text-[#617367]">The hospital lists 24/7 emergency and trauma care, pharmacy and laboratory services, alongside inpatient and outpatient care.</p><div className="mt-8 space-y-6">{[{ icon: HeartPulse, title: 'Emergency & trauma', copy: 'Hospital support for urgent care needs.' }, { icon: Microscope, title: 'Laboratory', copy: 'Diagnostic laboratory services to support the care team.' }, { icon: Pill, title: 'Pharmacy', copy: 'Pharmacy services within the hospital.' }].map(item => <div key={item.title} className="flex gap-4"><item.icon size={22} strokeWidth={1.5} className="mt-1 shrink-0 text-[#477456]" /><div><h3 className="text-lg font-medium">{item.title}</h3><p className="mt-1 text-sm text-[#617367]">{item.copy}</p></div></div>)}</div><p className="mt-7 text-sm leading-relaxed text-[#617367]">Specialist consultation times, test schedules and current facility availability are confirmed by reception.</p></div></section>
    <section className="border-t border-[#dce6d9] bg-[#eef3eb] py-14"><div className={`${shell} flex flex-col justify-between gap-7 lg:flex-row lg:items-center`}><div><h2 className="text-3xl font-medium tracking-[-.035em]">A closer look at the hospital.</h2><p className="mt-3 text-sm text-[#617367]">See our photographs and hear from the hospital team.</p></div><div className="flex flex-wrap gap-3"><button onClick={onExploreCommunity} className="inline-flex items-center gap-2 rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white">Photos & films <ArrowUpRight size={16} /></button><a href="tel:+919901711716" className="inline-flex items-center gap-2 rounded-full border border-[#9ab29e] px-6 py-3.5 text-sm font-semibold"><Phone size={16} /> Ask reception</a></div></div></section>
  </div>;
}
