import { ArrowRight, ArrowUpRight, Check, MapPin, Phone, ShieldCheck } from 'lucide-react';
import { Breadcrumbs } from '../common/Breadcrumbs';
import { branches } from '../../data/branches';
import { AllHealthPackages } from './AllHealthPackages';

interface SharedProps {
  onBackToHome: () => void;
  onExploreDepartments: () => void;
  onExploreDoctors: () => void;
  onExploreLocations: () => void;
  onSelectLocation: (id: string) => void;
  onOpenBooking: () => void;
  onExploreFounder?: () => void;
  onExploreInsurance?: () => void;
}

const shell = 'mx-auto max-w-[1400px] px-5 sm:px-10 lg:px-16';

export function InsurancePricingPage({ onBackToHome, onOpenBooking, onExploreLocations, onExploreInsurance }: SharedProps) {
  return <div className="bg-[#fbfaf6] text-[#17372b]">
    <div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'Insurance & pricing' }]} /></div>
    <section className={`${shell} grid gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24`}><div><p className="mb-5 text-xs font-bold tracking-[.18em] text-[#65816a]">PLAN WITH CONFIDENCE</p><h1 className="text-[clamp(3.5rem,6vw,6.6rem)] font-medium leading-[.98] tracking-[-.055em]">Clearer choices for your care.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#5c6e61]">Review the published health packages, ask about your coverage, and understand the next step before booking.</p><button onClick={onOpenBooking} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#214f38] px-7 py-3.5 text-sm font-semibold text-white">Ask about a visit <ArrowRight size={17} /></button></div><div className="aspect-[1.06] overflow-hidden rounded-[1.8rem] bg-[#e5eee2]"><img src="/clients/sri-lakshmi/36f2a4cf-home-page-banner.png" alt="Doctor discussing care with a patient" className="h-full w-full object-cover" /></div></section>
    <section className="bg-[#e8f0e5] py-16 sm:py-20"><div className={shell}><div className="max-w-2xl"><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">INSURANCE</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">Know what to ask before you visit.</h2><p className="mt-4 leading-relaxed text-[#607166]">Coverage depends on the insurer, plan, service, and clinic. Contact the hospital insurance desk to confirm your policy, treatment eligibility and pre-authorization.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ n: '01', title: 'Share your plan', copy: 'Provide the insurer and policy information when booking.' }, { n: '02', title: 'Confirm the service', copy: 'Ask which consultation, test, or procedure is planned.' }, { n: '03', title: 'Review the estimate', copy: 'Confirm any copay, deductible, or out of pocket amount before care.' }].map(item => <article key={item.n} className="rounded-2xl bg-white p-7"><span className="text-sm font-bold text-[#6f9273]">{item.n}</span><h3 className="mt-10 text-2xl font-medium">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#68796c]">{item.copy}</p></article>)}</div><button onClick={onExploreInsurance} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#275c40]">How cashless treatment works <ArrowUpRight size={16} /></button></div></section>
    <div className="border-y border-[#e4e9df] bg-white px-5 py-6 text-center text-sm leading-relaxed text-[#647368] sm:px-10"><ShieldCheck className="mr-2 inline-block align-middle text-[#477456]" size={18} /> Package prices and insurance names are published on the hospital website. Confirm current prices, coverage and approvals with the hospital.</div>
    <AllHealthPackages />
    <section className="bg-[#dcead8] py-16"><div className={`${shell} flex flex-col justify-between gap-6 md:flex-row md:items-center`}><div><h2 className="text-3xl font-medium tracking-[-.035em] sm:text-4xl">Choose a place to begin.</h2><p className="mt-2 text-[#58705d]">See our locations, then ask about the care you need.</p></div><button onClick={onExploreLocations} className="inline-flex self-start items-center gap-2 rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white">Find a location <ArrowUpRight size={16} /></button></div></section>
  </div>;
}

export function HowCareWorksPage({ onBackToHome, onExploreDepartments, onExploreDoctors, onExploreLocations, onOpenBooking }: SharedProps) {
  const steps = [
    { title: 'Find your starting point', copy: 'Browse a department or search for a doctor based on what you need.', action: 'Explore departments', run: onExploreDepartments },
    { title: 'Meet your doctor', copy: 'Read the doctor profile, specialty, and location before choosing a visit.', action: 'Meet the team', run: onExploreDoctors },
    { title: 'Choose how to visit', copy: 'Explore the hospital and its published group locations in Bengaluru.', action: 'See locations', run: onExploreLocations },
    { title: 'Plan your appointment', copy: 'Contact the hospital to confirm the specialist, date, time and consultation fee.', action: 'Plan a visit', run: onOpenBooking },
  ];
  return <div className="bg-[#fbfaf6] text-[#17372b]"><div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'How care works' }]} /></div><section className={`${shell} grid gap-12 py-16 lg:grid-cols-[1fr_1fr] lg:items-center lg:py-24`}><div><p className="mb-5 text-xs font-bold tracking-[.18em] text-[#65816a]">YOUR CARE JOURNEY</p><h1 className="text-[clamp(3.4rem,6vw,6.6rem)] font-medium leading-[.98] tracking-[-.055em]">A simpler way to find care.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#5c6e61]">Start with a question, find the right clinician, and choose the visit that works for you.</p></div><div className="aspect-[1.16] overflow-hidden rounded-[1.8rem] bg-[#e5eee2]"><img src="/clients/sri-lakshmi/0b3cc897-cardiology.png" alt="A doctor and patient discussing a care plan" className="h-full w-full object-cover" /></div></section><section className="bg-[#e8f0e5] py-20"><div className={shell}><div className="mb-10 max-w-xl"><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">FOUR STEPS</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">From first question to first visit.</h2></div><div className="grid gap-4 md:grid-cols-2">{steps.map((step, index) => <article key={step.title} className="flex min-h-72 flex-col rounded-2xl bg-white p-7 sm:p-9"><span className="text-sm font-bold text-[#6f9273]">0{index + 1}</span><h3 className="mt-8 text-3xl font-medium tracking-[-.035em]">{step.title}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-[#657568]">{step.copy}</p><button onClick={step.run} className="mt-auto inline-flex items-center gap-2 self-start pt-7 text-sm font-semibold text-[#275c40]">{step.action} <ArrowUpRight size={16} /></button></article>)}</div></div></section><section className={`${shell} grid gap-8 py-20 md:grid-cols-2 md:items-center`}><div><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">BEFORE YOU BOOK</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">The details matter.</h2></div><ul className="space-y-5 text-[#5e7064]">{['Check which location and visit type suits your care.', 'Confirm insurance coverage and any expected cost.', 'Bring prior records and a list of current medicines if relevant.'].map(point => <li key={point} className="flex items-start gap-3"><Check size={18} className="mt-0.5 shrink-0 text-[#477456]" />{point}</li>)}</ul></section></div>;
}

export function AboutUsPage({ onBackToHome, onExploreDepartments, onExploreDoctors, onExploreLocations, onExploreFounder }: SharedProps) {
  const steps = [
    { title: 'Our mission', copy: 'Make advanced medical services and technology accessible and affordable to the community.', action: 'Explore departments', run: onExploreDepartments },
    { title: 'Our medical team', copy: 'Meet the doctors listed by the hospital across medical and surgical specialties.', action: 'Meet the team', run: onExploreDoctors },
    { title: 'Sri Lakshmi Group', copy: 'The group lists hospitals in KR Puram, Kaggadasapura and Koramangala, including a Mother and Children Hospital.', action: 'See locations', run: onExploreLocations },
    { title: 'Our founder', copy: 'Dr. Sambashiva founded the hospital with a commitment to bring advanced healthcare closer to home.', action: 'From the founder', run: onExploreFounder },
  ];
  return <div className="bg-[#fbfaf6] text-[#17372b]"><div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'About us' }]} /></div><section className={`${shell} grid gap-12 py-16 lg:grid-cols-[1fr_1fr] lg:items-center lg:py-24`}><div><p className="mb-5 text-xs font-bold tracking-[.18em] text-[#65816a]">ABOUT SRI LAKSHMI</p><h1 className="text-[clamp(3.4rem,6vw,6.6rem)] font-medium leading-[.98] tracking-[-.055em]">Care for the KR Puram community.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#5c6e61]">Founded in 2002 by Dr. Sambashiva, Sri Lakshmi Super Speciality Hospital is a 50-bed hospital in KR Puram and part of the Sri Lakshmi Group of Hospitals.</p></div><div className="aspect-[1.16] overflow-hidden rounded-[1.8rem] bg-[#e5eee2]"><img src="/clients/sri-lakshmi/f22f9b39-1-1.png" alt="Sri Lakshmi Super Speciality Hospital exterior" className="h-full w-full object-cover" /></div></section><section className="bg-[#e8f0e5] py-20"><div className={shell}><div className="mb-10 max-w-xl"><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">OUR HOSPITAL</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">Built around accessible care.</h2></div><div className="grid gap-4 md:grid-cols-2">{steps.map((step, index) => <article key={step.title} className="flex min-h-72 flex-col rounded-2xl bg-white p-7 sm:p-9"><span className="text-sm font-bold text-[#6f9273]">0{index + 1}</span><h3 className="mt-8 text-3xl font-medium tracking-[-.035em]">{step.title}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-[#657568]">{step.copy}</p><button onClick={step.run} className="mt-auto inline-flex items-center gap-2 self-start pt-7 text-sm font-semibold text-[#275c40]">{step.action} <ArrowUpRight size={16} /></button></article>)}</div></div></section><section className={`${shell} grid gap-8 py-20 md:grid-cols-2 md:items-center`}><div><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">OUR PURPOSE</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">Advanced care, close to home.</h2></div><ul className="space-y-5 text-[#5e7064]">{['A 50-bed hospital serving families in KR Puram.', 'Emergency and trauma care, pharmacy and laboratory listed as open 24/7.', 'Cashless insurance enquiries supported by the hospital insurance desk.'].map(point => <li key={point} className="flex items-start gap-3"><Check size={18} className="mt-0.5 shrink-0 text-[#477456]" />{point}</li>)}</ul></section></div>;
}

export function ContactPage({ onBackToHome, onSelectLocation, onOpenBooking }: SharedProps) {
  return <div className="bg-[#fbfaf6] text-[#17372b]"><div className={`${shell} pt-7`}><Breadcrumbs items={[{ label: 'Home', onClick: onBackToHome }, { label: 'Contact' }]} /></div><section className={`${shell} grid gap-12 py-16 lg:grid-cols-[1fr_.9fr] lg:items-center lg:py-24`}><div><p className="mb-5 text-xs font-bold tracking-[.18em] text-[#65816a]">GET IN TOUCH</p><h1 className="text-[clamp(3.4rem,6vw,6.6rem)] font-medium leading-[.98] tracking-[-.055em]">We’re here to help you begin.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#5c6e61]">Ask about visits, explore a Bengaluru location, or start a booking.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={onOpenBooking} className="inline-flex items-center gap-2 rounded-full bg-[#214f38] px-6 py-3.5 text-sm font-semibold text-white">Plan a visit <ArrowRight size={17} /></button><a href="tel:+919901711716" className="inline-flex items-center gap-2 rounded-full border border-[#9ab29e] px-6 py-3.5 text-sm font-semibold"><Phone size={16} /> Call 99017 11716</a></div></div><div className="aspect-[1.13] overflow-hidden rounded-[1.8rem] bg-[#e5eee2]"><img src="/clients/sri-lakshmi/f22f9b39-1-1.png" alt="Sri Lakshmi Hospital care space" className="h-full w-full object-cover" /></div></section><section className="bg-[#e8f0e5] py-20"><div className={shell}><p className="mb-4 text-xs font-bold tracking-[.18em] text-[#65816a]">OUR LOCATIONS</p><h2 className="text-4xl font-medium tracking-[-.04em] sm:text-5xl">Find a place close to you.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{branches.map(branch => <button key={branch.id} onClick={() => onSelectLocation(branch.id)} className="flex min-h-40 flex-col rounded-2xl bg-white p-6 text-left transition-transform hover:-translate-y-1"><MapPin size={19} className="text-[#5d8065]" /><h3 className="mt-5 text-xl font-medium">{branch.name}</h3><span className="mt-auto inline-flex items-center gap-2 pt-4 text-sm font-semibold text-[#275c40]">View details <ArrowUpRight size={16} /></span></button>)}</div></div></section></div>;
}
